- name: Build and analyze
  shell: powershell
  run: |
    .\.sonar\scanner\dotnet-sonarscanner begin `
      /k:"TU_PROJECT_KEY" `
      /o:"TU_ORGANIZACION" `
      /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
      /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    dotnet build Asisya.ProductsApi.csproj
    .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
